export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_REFRESH_REQUESTED = 'AUTH_REFRESH_REQUESTED';

export const AUTH_LOGOUT_REQUESTED = 'AUTH_LOGOUT_REQUESTED';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

export const TOGGLE_MOBILE_MENU = 'TOGGLE_MOBILE_MENU';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const BRANDS_REQUESTED = 'BRANDS_REQUESTED';
export const BRANDS_SUCCESS = 'BRANDS_SUCCESS';
export const BRANDS_FAILURE = 'BRANDS_FAILURE';

export const CATEGORIES_REQUESTED = 'CATEGORIES_REQUESTED';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';

export const MODELS_REQUESTED = 'MODELS_REQUESTED';
export const MODELS_SUCCESS = 'MODELS_SUCCESS';
export const MODELS_FAILURE = 'MODELS_FAILURE';

export const PROBLEMS_REQUESTED = 'PROBLEMS_REQUESTED';
export const PROBLEMS_SUCCESS = 'PROBLEMS_SUCCESS';
export const PROBLEMS_FAILURE = 'PROBLEMS_FAILURE';

export const PLACEMARKS_REQUESTED = 'PLACEMARKS_REQUESTED';
export const PLACEMARK_SUCCESS = 'PLACEMARK_SUCCESS';
export const PLACEMARK_FAILURE = 'PLACEMARK_FAILURE';

export const QUESTIONS_REQUESTED = 'QUESTIONS_REQUESTED';
export const QUESTIONS_SUCCESS = 'QUESTIONS_SUCCESS';
export const QUESTIONS_FAILURE = 'QUESTIONS_FAILURE';

export const CREATE_TASK_REQUESTED = 'CREATE_TASK_REQUESTED';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';
export const CREATE_TASK_CLEAR = 'CREATE_TASK_CLEAR';

export const TASKS_REQUESTED = 'TASKS_REQUESTED';
export const TASKS_SUCCESS = 'TASKS_SUCCESS';
export const TASKS_FAILURE = 'TASKS_FAILURE';

export const MORE_TASKS_REQUESTED = 'MORE_TASKS_REQUESTED';
export const MORE_TASKS_SUCCESS = 'MORE_TASKS_SUCCESS';
export const MORE_TASKS_FAILURE = 'MORE_TASKS_FAILURE';
